### ISSUE TITLE
output files

### ISSUE THREAD

**Issue by dhjpolymath** [km-git-acc/dbn_upper_bound#19]
The output files without 4 numbers after them can be deleted. The newer files in "numbers" include updates of these.

**Comment by km-git-acc** [comment]
I was looking at the file out_01_1000_20_22.txt, and noticed the effects of decreasing accuracy with increasing z.
for eg.

0.2 | 125 | 558.4577961 | 1.956309
0.2 | 126 | 564.9305993 | 6.472803
0.2 | 127 | 561.9850395 | -2.94556
0.2 | 128 | 569.6719476 | 7.686908

The T heights should always increase, but here the 3rd line shows a negative difference compared to the previous zero.

The corresponding H0 zeroes are (calculated as 2*zeta)
558.458501856, 564.93022953, 566.422371466, 569.671927962

**Comment by km-git-acc** [comment]
Which likely means the alternate way of calculating Ht (as discussed in another thread) will be needed.

**Comment by km-git-acc** [comment]
Another thing that could be tried is to vary t slowly for a certain root.
So for example if we want to calculate z_128 for H_0.2, we could first calculate it for H_0.01 (or maybe even finer), use the root for H_0.01 to calculate the root for H_0.02, and so on till we reach H_0.2. This increases the computation time if we directly want to get the root for H_0.2, but if we are anyways calculating the roots for small t step sizes, we could rearrange the computation this way.

I think even this trick would have its limits, since the key question is whether the current implementation of Ht_real is accurate enough for large z.

**Comment by dhjpolymath** [comment]
A new script will start to run with the quad parameters edited and possibly a recursive computation of zeros.

**Comment by dhjpolymath** [comment]
Here is the recursive script which will be tested with upper limit '20' instead of '10' for t=.20-.22 with the indices shifted.

from scipy.optimize import fsolve
from first_1000_zeta import first_1000_zeta
from utility import Ht_real

import sys

orig_stdout = sys.stdout
f = open('out_0001_1000_01_49.txt', 'w')
sys.stdout = f


first_1000_H0_zero = [x*2 for x in first_1000_zeta]

# k is a stopping parameter (1<=k<=1000) which corresponds to the kth zero of
# the H_0 fn while l is the starting parameter. Default is 1, 1000.

l = 1

k = 1000

A=first_1000_H0_zero = [x*2 for x in first_1000_zeta]

for j in range(1, 5):
    t = .01*j
    B=[]
    for i, nearby_root in enumerate(first_1000_H0_zero[l-1:k-1]):
        Ht_root = fsolve(Ht_real, nearby_root, args=(t,))[0]
        B=B+[]
        print(t, i, Ht_root)
    A=B

sys.stdout = orig_stdout
f.close()

**Comment by dhjpolymath** [comment]
No improvement increasing quad parameter from '10' to '20'. The first list is the new calculation.

0.2 291 1061.733835768
0.2 292 1065.376366056
0.2 293 1062.0451744199909
0.2 294 1072.9836845795646
0.2 295 1072.9836869403289
0.2 296 1076.672959157882
0.2 297 1063.0312414193863
0.2 298 1029.2509786306596
0.2 299 1083.3828961407182
0.2 300 1088.647780202
0.2 301 1091.273666498
0.2 302 1095.0013076963107
0.2 303 1094.863732916828
0.2 304 1098.995135126
0.2 305 1103.4903440488827
0.2 306 1104.0414083131875
0.2 307 1103.302139864266
0.2 308 1103.4906439879264
0.2 309 1083.3828961354761
0.2 310 1115.129318344
0.2 311 1103.298729938656

vs

0.2 291 1062.0451500545942
0.2 292 1065.376366056
0.2 293 1067.5138754044026
0.2 294 1072.9836690080374
0.2 295 1072.983681469106
0.2 296 1078.454710632562
0.2 297 1078.4547033371018
0.2 298 1078.454688470423
0.2 299 1083.382896138277
0.2 300 1089.4007976941637
0.2 301 1089.4007954525541
0.2 302 1089.4008001277236
0.2 303 1094.8760958011508
0.2 304 1098.995135126
0.2 305 1103.3532751362598
0.2 306 1103.353228238824
0.2 307 1107.529944238
0.2 308 1103.3532746600386
0.2 309 1083.382896142383
0.2 310 1116.7235014241933
0.2 311 1105.83171144044

**Comment by dhjpolymath** [comment]
Note: the above data was not from the code above as the only computations were done with t=.20 so there were not close values to search near.

**Comment by km-git-acc** [comment]
yeah the T heights are still fluctuating

I had written some code for I_t_theta (not fully verified yet), which forms part of the more accurate calculation in eqn 2) and 3). 

def Ittheta(b,beta,t,theta):
   def Ittheta_integrand(u,b,beta,t):
       return exp(t*u*u - beta*exp(4*u) + 1j*b*u)
   def real_func(a1,a2,a3,a4): return scipy.real(Ittheta_integrand(a1,a2,a3,a4))
   def imag_func(a1,a2,a3,a4): return scipy.imag(Ittheta_integrand(a1,a2,a3,a4))   
   real_part = quad(real_func, 1j*theta, np.inf + 1j*theta, args=(b,beta,t))
   imag_part = quad(imag_func, 1j*theta, np.inf + 1j*theta, args=(b,beta,t))
   return (real_part[0] + 1j*imag_part[0], real_part[1], imag_part[1])


def Ittheta(b,beta,t,theta=PI/8):
   def Ittheta_integrand(v,b,beta,t):
       return exp(t*(v+1j*theta)*(v+1j*theta) - beta*exp(4*(v+1j*theta)) + 1j*b*(v+1j*theta))
   def real_func(a1,a2,a3,a4): return scipy.real(Ittheta_integrand(a1,a2,a3,a4))
   def imag_func(a1,a2,a3,a4): return scipy.imag(Ittheta_integrand(a1,a2,a3,a4))   
   real_part = quad(real_func, 0, 1, args=(b,beta,t))
   imag_part = quad(imag_func, 0, 1, args=(b,beta,t))
   return (real_part[0] + 1j*imag_part[0], real_part[1], imag_part[1])

The first function doesnt work with quad since I am integrating along a non real path. The second one gives some values but their accuracy has to be checked. This is only the I function in eqn 3), not the K function in eqn 2) which uses the I function . Ht can be computed only after implementing K

**Comment by km-git-acc** [comment]
Does the editor remove the indentation. Pasting it differently again

def Ittheta(b,beta,t,theta=PI/8):
----def Ittheta_integrand(v,b,beta,t):
--------return exp(t*(v+1j*theta)*(v+1j*theta) - beta*exp(4*(v+1j*theta)) + 1j*b*(v+1j*theta))
----def real_func(a1,a2,a3,a4): return scipy.real(Ittheta_integrand(a1,a2,a3,a4))
----def imag_func(a1,a2,a3,a4): return scipy.imag(Ittheta_integrand(a1,a2,a3,a4))   
----real_part = quad(real_func, 0, 1, args=(b,beta,t))
----imag_part = quad(imag_func, 0, 1, args=(b,beta,t))
----return (real_part[0] + 1j*imag_part[0], real_part[1], imag_part[1])
